#!/usr/bin/env bash

#计算自身所处位置，以定位其他脚本文件
dirname_tmp=$(dirname "$0" )
script_path=$(cd "$dirname_tmp" && pwd )
cd "$script_path"

# 常量配置
LOCAL_BRANCH="master"
REMOTE_BRANCH="master"
REPO_LIST_FILE="repolist.txt"
DEFAULT_COMMIT_MESSAGE="自动提交"

#添加 git logs 指令，用不那么反人类的方式显示提交列表
git config --local alias.logs "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"
#取消转意，这样git status显示时就不会把中文转意为\unicode编码数字
git config --local core.quotepath false
git config --local user.name Gnosis
git config --local user.email gnosis@pleroma.com

#如果没有提交消息，默认为"自动提交"，也可传一个自定义提交信息
if [ $# -eq 0 ]; then
  message="$DEFAULT_COMMIT_MESSAGE"
elif [ $# -eq 1 ]; then
  message="$1"
else
  echo "用法: $0 [提交信息]"
  exit 1
fi

#添加所有文件并提交
git add -A
git commit -m "$message"

#提取本机IP（用于过滤掉目标IP是本机的仓库）=
if [[ "$(uname -a)" =~ "Darwin" ]];then #如果是苹果mac系统
	local_ips=$(ifconfig|grep -Eo 'inet *((1?[0-9]{2}|2[0-4][0-9]|25[0-6]|[0-9])\.){3}(1?[0-9]{2}|2[0-4][0-9]|25[0-6]|[0-9])'|grep -Eo '((1?[0-9]{2}|2[0-4][0-9]|25[0-6]|[0-9])\.){3}(1?[0-9]{2}|2[0-4][0-9]|25[0-6]|[0-9])')
else #如果是其他linux系统
	local_ips=$(ip address show scope global |grep -Eo 'inet *((1?[0-9]{2}|2[0-4][0-9]|25[0-6]|[0-9])\.){3}(1?[0-9]{2}|2[0-4][0-9]|25[0-6]|[0-9])'|grep -Eo '((1?[0-9]{2}|2[0-4][0-9]|25[0-6]|[0-9])\.){3}(1?[0-9]{2}|2[0-4][0-9]|25[0-6]|[0-9])')
fi

#遍历仓库列表文件
for i in `cat "$script_path/$REPO_LIST_FILE"`
do
	first_char=$(echo $i|grep -o "#" )
	if [ "$first_char" != "#" ] ;then
		ips_in_repo=$(echo $i|grep -Eo -m 1 '((1?[0-9]{2}|2[0-4][0-9]|25[0-6]|[0-9])\.){3}(1?[0-9]{2}|2[0-4][0-9]|25[0-6]|[0-9])') #提取出仓库地址里面的ip
		ip="";for m in $ips_in_repo ;do ip=$m;break;done #过滤出第一个ip
		mark=0;for lip in $local_ips;do if [ "$ip" == "$lip" ];then mark=1;fi;done ##判断本机ip是否匹配
		if [ "$mark" == "1" ];then continue;fi ##调到下一个仓库

		echo -e "\033[32m\033[01m git push $i ${LOCAL_BRANCH}:${REMOTE_BRANCH} \033[0m"
		git push "$i" "${LOCAL_BRANCH}:${REMOTE_BRANCH}"
	fi
done